# SPDX-License-Identifier: Apache-2.0
"""
Shared synthetic-data builders for the weight2ternary tests. No downloads, no GPU -
everything here fabricates small tensors/directories with KNOWN structure so each
test asserts against a constructed truth rather than a real checkpoint.
"""
import os
import sys

import torch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from weight2ternary.data_utils.features import build_features  # noqa: E402


def make_group_ternary(out_f=64, in_f=512, group=128, sparsity=0.4, seed=0):
    """A synthetic clean group-scaled ternary tensor: returns (qat_w, code, scales)."""
    gen = torch.Generator().manual_seed(seed)
    code = torch.randint(-1, 2, (out_f, in_f), generator=gen).float()
    keep = torch.rand(out_f, in_f, generator=gen) >= max(0.0, sparsity - 1 / 3)
    code = code * keep
    scales = torch.rand(out_f, in_f // group, generator=gen) * 0.05 + 0.01
    qat_w = code * scales.repeat_interleave(group, dim=1)
    return qat_w, code, scales


def make_threshold_pair(out_f=64, in_f=512, group=128, tau=0.6, seed=0):
    """A synthetic (base, code) pair where the TRUE code is the group-threshold rule
    at `tau` - so B2 at that tau is perfect and B1 (tau=0.5) is wrong exactly on the
    |w|/group_absmean band between 0.5 and tau."""
    from weight2ternary.eval_utils.baselines import ternarize_group_threshold
    gen = torch.Generator().manual_seed(seed)
    base = torch.randn(out_f, in_f, generator=gen) * 0.05
    code = ternarize_group_threshold(base, tau, group)
    return base, code


def make_batch(bsz=16, seg_len=256, group=64, tau=0.6, seed=0):
    """A full synthetic training batch (same keys as PairSegmentSampler output),
    with the true code generated by the tau-threshold rule."""
    from weight2ternary.eval_utils.baselines import (baseline_group_scales,
                                                     ternarize_group_threshold,
                                                     ternarize_per_group_absmean)
    gen = torch.Generator().manual_seed(seed)
    base = torch.randn(bsz, seg_len, generator=gen) * 0.05
    code = ternarize_group_threshold(base, tau, group)
    baseline_code = ternarize_per_group_absmean(base, group)
    scales = base.abs().view(bsz, -1, group).mean(dim=2) * 2.0

    feat_ctx = {
        'col_absmean_seg': torch.full((seg_len,), 0.04),
        'col_norm_seg': torch.full((seg_len,), 1.0),
        'row_absmean': base.abs().mean(dim=1),
        'row_norm': base.norm(dim=1),
        'mean_col_norm': 1.0,
        'mean_row_norm': float(base.norm(dim=1).mean().item()),
        'tensor_absmean': float(base.abs().mean().item()),
        'depth_frac': 0.5,
        'proj': 0,
    }
    batch = {
        'base': base,
        'code': code.long(),
        'scales': scales,
        'baseline_code': baseline_code.long(),
        'baseline_scales': baseline_group_scales(base, baseline_code, group),
        'layer': 'synthetic.layers.0.self_attn.q_proj.weight',
        'feat_ctx': feat_ctx,
    }
    batch['features'] = build_features(
        base, feat_ctx['col_absmean_seg'], feat_ctx['col_norm_seg'],
        feat_ctx['row_absmean'], feat_ctx['row_norm'], feat_ctx['mean_col_norm'],
        feat_ctx['mean_row_norm'], feat_ctx['tensor_absmean'],
        feat_ctx['depth_frac'], feat_ctx['proj'], group_size=group)
    return batch


def write_synthetic_snapshot(snapshot_dir, layer_tensors):
    """Write {param_name: tensor} as a single-shard HF-style snapshot dir."""
    from safetensors.torch import save_file
    os.makedirs(snapshot_dir, exist_ok=True)
    save_file({k: v.contiguous() for k, v in layer_tensors.items()},
              os.path.join(snapshot_dir, 'model.safetensors'))
    return snapshot_dir


def write_synthetic_pair_dir(out_dir, n_depths=8, out_f=64, in_f=512, group=128,
                             seed=0):
    """Fabricate an extracted-pair directory (shards + manifest.csv) the sampler can
    consume: one q_proj layer per depth, true code from the group-threshold rule."""
    import pandas as pd
    from safetensors.torch import save_file
    from weight2ternary.data_utils.extract import derive_code_and_scales

    os.makedirs(out_dir, exist_ok=True)
    rows = []
    for depth in range(n_depths):
        base, code = make_threshold_pair(out_f, in_f, group, tau=0.6, seed=seed + depth)
        scales = base.abs().view(out_f, -1, group).mean(dim=2) * 2.0
        qat = code * scales.repeat_interleave(group, dim=1)
        code_rec, scales_rec, _ = derive_code_and_scales(qat, group)

        name = f'model.layers.{depth}.self_attn.q_proj.weight'
        shard = name.replace('.', '_') + '.safetensors'
        save_file({
            'base': base.contiguous(),
            'code': code_rec.contiguous(),
            'scales': scales_rec.contiguous(),
            'col_absmean': base.abs().mean(dim=0).contiguous(),
            'col_norm': base.norm(dim=0).contiguous(),
            'row_absmean': base.abs().mean(dim=1).contiguous(),
            'row_norm': base.norm(dim=1).contiguous(),
        }, os.path.join(out_dir, shard))
        rows.append({'layer': name, 'layer_type': 'attention_qkvo', 'proj_id': 0,
                     'depth': depth, 'out_features': out_f, 'in_features': in_f,
                     'sparsity': float((code_rec == 0).float().mean().item()),
                     'tensor_absmean': float(base.abs().mean().item()),
                     'recon_err': 0.0, 'shard': shard})
    pd.DataFrame(rows).to_csv(os.path.join(out_dir, 'manifest.csv'), index=False)
    return out_dir
